-- ============================================================================
-- 어뷰티 — 제품 관리(Product CMS) 테이블 (Supabase SQL Editor에 그대로 붙여넣고 실행)
-- ============================================================================

create table if not exists products (
  id            bigint generated by default as identity primary key,

  product_name  text not null,
  category      text,
  concern_tags  jsonb,          -- 고민 태그 배열, 예: ["탈모", "곱슬", "손상모"]
  image_url     text,
  buy_link      text,

  created_at    timestamptz not null default now()
);

create index if not exists idx_products_category   on products (category);
create index if not exists idx_products_created_at on products (created_at desc);

-- ============================================================================
-- RLS(Row Level Security) — events 테이블과 동일한 보안 정책
--
-- anon key는 브라우저 번들에 그대로 노출되는 공개 키다. 제품 CRUD는 어드민 전용
-- 기능이므로 anon에게는 어떤 권한도 주지 않고, service_role 키를 쓰는 서버 API
-- 라우트(app/api/admin/products/**)를 통해서만 등록/조회/수정/삭제한다.
-- ============================================================================

alter table products enable row level security;

-- 의도적으로 anon 대상 정책을 만들지 않음 (anon은 조회/등록/수정/삭제 모두 불가)
