-- ============================================================================
-- 어뷰티 — 이벤트 트래킹 테이블 (Supabase SQL Editor에 그대로 붙여넣고 실행)
-- ============================================================================

create table if not exists events (
  id                          bigint generated by default as identity primary key,

  -- 유저 식별
  user_id                     text,           -- kakao_user_id가 있으면 그 값, 없으면 anonymous_id
  anonymous_id                text not null,  -- localStorage 기반 익명 ID
  kakao_user_id               text,           -- 카카오 로그인 시 부여

  -- 유입 경로 (UTM 어트리뷰션 — first-touch로 모든 이벤트에 동승)
  landing_id                  text,           -- 예: 'mbti_test', 'style'
  source                      text,           -- utm_source 기반
  utm_medium                  text,           -- utm_medium
  utm_campaign                text,           -- utm_campaign (어느 쇼츠/캠페인 유입인지)
  content_id                  text,

  -- 세션/진단
  session_id                  text,
  diagnosis_type              text,
  answers                     jsonb,          -- 설문 답변 (배열/객체)
  concern_tags                jsonb,          -- 고민 태그 배열
  result_type                 text,           -- 도출된 결과 유형
  recommended_product_groups  jsonb,          -- 추천된 제품군 배열

  -- 이벤트 본문
  event_name                  text not null,  -- landing_view / diagnosis_start / answer_selected / diagnosis_complete / product_clicked / login_clicked
  event_time                  timestamptz not null default now(),

  -- 커머스/전환
  product_group_clicked       text,
  product_id_clicked          text,
  cta_clicked                 text,
  marketing_consent           boolean,
  kakao_channel_added         boolean,

  -- 스키마에 없는 임의 이벤트 컨텍스트(productId, coreKey, ui 위치, postId 등)
  meta                        jsonb,

  created_at                  timestamptz not null default now()
);

-- 어드민 대시보드 집계 쿼리(랜딩별/이벤트별/최신순)에 쓰이는 조회 패턴에 맞춘 인덱스
create index if not exists idx_events_event_name   on events (event_name);
create index if not exists idx_events_landing_id   on events (landing_id);
create index if not exists idx_events_anonymous_id on events (anonymous_id);
create index if not exists idx_events_created_at   on events (created_at desc);
create index if not exists idx_events_utm_campaign on events (utm_campaign);
create index if not exists idx_events_utm_medium   on events (utm_medium);

-- ============================================================================
-- RLS(Row Level Security) — anon key는 "쓰기 전용"으로 제한
--
-- NEXT_PUBLIC_SUPABASE_ANON_KEY는 브라우저 번들에 그대로 노출되는 공개 키다.
-- SELECT를 anon에게 허용하면 누구나 개발자도구에서 이 키를 꺼내
-- 전체 유저의 행동 데이터(answers, concern_tags 등)를 그대로 읽어갈 수 있다.
-- 그래서 anon에게는 INSERT만 허용하고, 어드민 조회는 서버(API 라우트)에서
-- RLS를 우회하는 service_role 키로만 수행한다.
-- ============================================================================

alter table events enable row level security;

create policy "anon can insert events"
  on events for insert
  to anon
  with check (true);

-- 의도적으로 SELECT/UPDATE/DELETE 정책은 만들지 않음 (anon은 조회/수정/삭제 불가)
